### ISSUE TITLE
Decred tx builder: AttributeError: 'NoneType' object has no attribute 'to_bytes'

### ISSUE THREAD

**Issue by dmorris99** [summa-tx/riemann#58]
Hi, having issues with Decred transaction builder. My code and output is below.

Basically, seems to be failing on the highlighted line. Any idea what I could be doing wrong?

Many thanks, and v. nice library 👍 

---

``import requests #test

import riemann
from riemann import simple
from riemann.encoding import addresses
from riemann.tx import tx_builder as tb
from riemann.networks import networks as networks

riemann.select_network('decred_main')

tx_id = '3e0bdb15dd2a338da0865f5422b976cd34737dadd276cc793ecd21b5fad45dc3' # Previous transaction hash
tx_index = 7 # UTXO index to use
**tx_outpoint = simple.outpoint(tx_id, tx_index) # Generate outpoint**
tx_in = simple.unsigned_input(tx_outpoint, sequence=0xFFFFFFFE) # Generate TxIn
receiving_address = 'DsV2C5es3sDrkZbQdaTVfwZbSvef3r8St37' # Address to receive 
input_value = 0.001 # amount to send
tx_fee = 0.0001 # Allocate for miner
tx_out = simple.output(input_value - tx_fee, receiving_address)
tx_return_output = tb.make_op_return_output('made with ❤ by riemann'.encode('utf-8')) # Completely optional memo
tx = simple.unsigned_tx([tx_in], [tx_out, tx_return_output]) # Create unsigned transaction

print (tx)
print (txtx.hex())
``

Output:

C:\SCP\src\riemann>py test.py
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    **tx_outpoint = simple.outpoint(tx_id, tx_index) # Generate outpoint**
  File "C:\SCP\src\riemann\riemann\simple.py", line 85, in outpoint
    return tb.make_outpoint(tx_id_le, index, tree)
  File "C:\SCP\src\riemann\riemann\tx\tx_builder.py", line 172, in make_outpoint
    tree=utils.i2le_padded(tree, 1))
  File "C:\SCP\src\riemann\riemann\utils.py", line 26, in i2le_padded
    return number.to_bytes(length, 'little')
AttributeError: 'NoneType' object has no attribute 'to_bytes'

**Comment by dmorris99** [comment]
I got past this error by specifying a value (1) for parameter tree to fn. simple.outpoint (although no idea if this is a valid value!)

Now get the following exception on the next call: tx_in = simple.unsigned_input(tx_outpoint, sequence=0xFFFFFFFE) # Generate TxIn

C:\SCP\src\riemann>py test.py
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    tx_in = simple.unsigned_input(tx_outpoint, sequence=0xFFFFFFFE) # Generate TxIn
  File "C:\SCP\src\riemann\riemann\simple.py", line 112, in unsigned_input
    sequence=sequence)
  File "C:\SCP\src\riemann\riemann\tx\tx_builder.py", line 193, in make_legacy_input
    sequence=utils.i2le_padded(sequence, 4))
  File "C:\SCP\src\riemann\riemann\tx\tx.py", line 278, in __init__
    self.validate_bytes(outpoint, 36)
  File "C:\SCP\src\riemann\riemann\tx\tx.py", line 132, in validate_bytes
    .format(length, type(data), len(data)))
ValueError: Expected byte-like object with length 36. Got <class 'riemann.tx.tx.DecredOutpoint'> with length 37.

**Comment by prestwich** [comment]
> I got past this error by specifying a value (1) for parameter tree to fn. simple.outpoint (although no idea if this is a valid value!)

Decred outpoints specify a tx tree. Generally this will be 0 for normal transactions, and 1 for transactions involving staking/tickets.

> Now get the following exception on the next call: tx_in = simple.unsigned_input(tx_outpoint, sequence=0xFFFFFFFE) # Generate TxIn

Just opened #59 to address this. Should be merged later today.

**Comment by prestwich** [comment]
Should be fixed now :+1:

**Comment by waliguder** [comment]
Please help me find out how to solve this problem [#87](https://github.com/summa-tx/riemann/issues/87) thank you very much！！
@dmorris99 @prestwich
